apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "preview.fullname" . }}
  labels:
    app: {{ template "preview.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 35%
  template:
    metadata:
      labels:
        app: {{ template "preview.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imagerepo }}:{{ .Values.image.imagetag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.service.serviceAccount }}
      serviceAccountName: {{ .Values.service.serviceAccount }}
{{- end }}
